
hello_the_world:
    path:     /hello-world
    defaults: { _controller: OCPlatformBundle:Advert:index }

bye_bye_world:
    path:     /bye-bye-world
    defaults: {_controller: OCPlatformBundle:Advert:exit }